### ISSUE TITLE
Fix units on velocity colorbar

### ISSUE THREAD

**Issue by BrianOBlanton** [RENCI/adcirc2mbtiles#1]
![image](https://user-images.githubusercontent.com/2234435/130628814-e2f0c4a9-0527-4910-a304-94565133d84e.png)

**Comment by jmpmcmanus** [comment]
Hi Brian,
The swan and maxwvel where switched. I fixed this problem and it will be there in the next build of the docker image, which should be today. I've also increased the font size and cropped and area around the colorbar. There are a few other things I'm looking into.
Jim
    On Tuesday, August 24, 2021, 09:52:11 AM EDT, Brian O. Blanton ***@***.***> wrote:  
 
 




—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BrianOBlanton** [comment]
This issue now includes cropping of the colorbar image and increasing the font size.    Other things should be entered as a new issue for tracking.

**Comment by jmpmcmanus** [comment]
Okay
    On Tuesday, August 24, 2021, 10:52:58 AM EDT, Brian O. Blanton ***@***.***> wrote:  
 
 


This issue now includes cropping of the colorbar image and increasing the font size. Other things should be entered as a new issue for tracking.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BrianOBlanton** [comment]
Jim, has this fix been pushed to production?

**Comment by jmpmcmanus** [comment]
No. I'm testing the scripts in Jupyter notebook. If you okay them, I will implement it in the adcirc2geotiff.py script.
________________________________

**Comment by BrianOBlanton** [comment]
yes please do. thanks!

**Comment by jmpmcmanus** [comment]
Hi Brian,

I've updated the code in adcirc2mbtiles.py to use discrete colors. I've tested the code on my own machine, and everything looks okay. I want to do some additional checks before pushing the docker image to docker hub.

I have something related to purchasing a house, that I need to do tomorrow morning. I will be back before 12pm.

Jim
________________________________

**Comment by BrianOBlanton** [comment]
NP, Jim.  this is all progressing swiftly.  I've learned more about the CERA/LSU situation that I'll share this week, and Stan has asked me what resources we need.  So all is good.  Take your time with the house.  I'm exhausted from the weekend activities, and will not be around much tomorrow.

Cheers,

[signature_577695696]

Brian O. Blanton, Ph.D.
Director of Earth Data Sciences
Oceanographer
Renaissance Computing Institute
University of North Carolina at Chapel Hill
100 Europa Drive
Suite 540 Chapel Hill, NC, 27517

***@***.******@***.***>
919-445-9620 (O)

[signature_1645074049]

________________________________

**Comment by jmpmcmanus** [comment]
Made these changes.
