### ISSUE TITLE
reduce number of colors in colorbars and images 

### ISSUE THREAD

**Issue by BrianOBlanton** [RENCI/adcirc2mbtiles#2]
make colormap more discrete so that it is easier to discern values on the map.  Please try 32 colors.

**Comment by jmpmcmanus** [comment]
Okay. 
    On Tuesday, August 24, 2021, 10:51:37 AM EDT, Brian O. Blanton ***@***.***> wrote:  
 
 


make colormap more discrete so that it is easier to discern values on the map. Please try 32 colors.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jmpmcmanus** [comment]
Added discrete colors to adcirc2geotiff.py
